/**
 * Clear cases — names that share letters or sounds but are not real problems.
 *
 * Failing any of these is a **false positive**: the engine scared somebody away
 * from a perfectly good name. §54 counts this as a genuine cost, not a safe
 * default. A tool that flags everything is exactly as useless as one that flags
 * nothing, and considerably more annoying.
 */
import type { GoldenCase } from './types'

const SECURITY = 'Secure developer secrets manager with encryption'
const BANKING = 'Mobile banking app and current account'
const APPAREL = 'Streetwear clothing and apparel brand'
const RESTAURANT = 'Neighbourhood restaurant and cafe'

export const CLEAR_CASES: GoldenCase[] = [
  /* ── the §18 headline case: same name, unrelated field ────────────────── */
  {
    id: 'industry-001',
    kind: 'clear',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'ENVRYN CLOTHING',
    matchDescription: 'Streetwear clothing and apparel brand',
    legallyWeighted: true,
    expect: { maxIndustry: 30, severityAtMost: 'high' },
    tags: ['unrelated-industry', 'roadmap-example'],
    note: 'The §18 example. Exact spelling, unrelated field — must not be critical.',
  },
  {
    id: 'industry-002',
    kind: 'clear',
    candidate: 'Keyora',
    category: 'saas',
    description: SECURITY,
    match: 'Keyora',
    matchDescription: 'Artisan bakery and coffee shop',
    legallyWeighted: true,
    expect: { maxIndustry: 30, severityAtMost: 'high' },
    tags: ['unrelated-industry'],
    note: 'A bakery is not a competitor to a secrets manager.',
  },
  {
    id: 'industry-003',
    kind: 'clear',
    candidate: 'Vaultara',
    category: 'developer_tool',
    description: SECURITY,
    match: 'Vaultara',
    matchDescription: 'Luxury furniture and interior decor retailer',
    legallyWeighted: true,
    expect: { maxIndustry: 30, severityAtMost: 'high' },
    tags: ['unrelated-industry'],
    note: 'Furniture and developer tooling share nothing but the string.',
  },
  {
    id: 'industry-004',
    kind: 'clear',
    candidate: 'Lockryn',
    category: 'restaurant',
    description: RESTAURANT,
    match: 'Lockryn',
    matchDescription: 'Enterprise cybersecurity and encryption software',
    legallyWeighted: true,
    expect: { maxIndustry: 30, severityAtMost: 'high' },
    tags: ['unrelated-industry'],
    note: 'The reverse direction: a security firm is no threat to a restaurant.',
  },
  {
    id: 'industry-005',
    kind: 'clear',
    candidate: 'Stripe',
    category: 'fashion',
    description: APPAREL,
    match: 'Stripe',
    matchDescription: 'Payment processing and financial infrastructure',
    legallyWeighted: true,
    expect: { maxIndustry: 30, severityAtMost: 'high' },
    tags: ['unrelated-industry', 'famous-brand'],
    note: 'Even a famous brand is a weaker concern outside its own field.',
  },

  /* ── coincidental non-commercial matches ──────────────────────────────── */
  {
    id: 'noncomm-001',
    kind: 'clear',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envryn',
    matchDescription: 'village in northern France',
    expect: { industryUnknown: true, severityAtMost: 'high' },
    tags: ['non-commercial', 'place'],
    note: 'A village is not a naming conflict and must not classify as an industry.',
  },
  {
    id: 'noncomm-002',
    kind: 'clear',
    candidate: 'Keyora',
    category: 'saas',
    description: SECURITY,
    match: 'Keyora',
    matchDescription: 'given name of Greek origin',
    expect: { industryUnknown: true, severityAtMost: 'high' },
    tags: ['non-commercial', 'person'],
    note: 'A personal name shares the string and nothing else.',
  },
  {
    id: 'noncomm-003',
    kind: 'clear',
    candidate: 'Stripe',
    category: 'saas',
    description: 'Payment processing platform',
    match: 'stripe',
    matchDescription: "narrow white marking down a horse's face",
    expect: { industryUnknown: true, severityAtMost: 'high' },
    tags: ['non-commercial', 'common-word'],
    note: 'The dictionary sense of a common word is not a competitor.',
  },
  {
    id: 'noncomm-004',
    kind: 'clear',
    candidate: 'Gremlin',
    category: 'saas',
    description: 'Chaos engineering and reliability testing',
    match: 'Gremlin',
    matchDescription: 'fictional character in a film franchise',
    expect: { maxIndustry: 20, severityAtMost: 'high' },
    tags: ['non-commercial', 'fiction'],
    note: 'A fictional character classifies as entertainment via "film", which is correct. What matters is that it scores as essentially unrelated to engineering software.',
  },

  /* ── genuinely different names ────────────────────────────────────────── */
  {
    id: 'distinct-001',
    kind: 'clear',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Quicksilver',
    matchDescription: 'Computer security software',
    legallyWeighted: true,
    expect: { maxOverall: 45, severityAtMost: 'low' },
    tags: ['distinct'],
    note: 'Same industry, unrelated name. Industry alone must not raise severity.',
  },
  {
    id: 'distinct-002',
    kind: 'clear',
    candidate: 'Vaultara',
    category: 'saas',
    description: SECURITY,
    match: 'Bluebird',
    matchDescription: 'Encryption and key management platform',
    legallyWeighted: true,
    expect: { maxOverall: 45, severityAtMost: 'low' },
    tags: ['distinct'],
    note: 'No shared letters of consequence.',
  },
  {
    id: 'distinct-003',
    kind: 'clear',
    candidate: 'Lockryn',
    category: 'saas',
    description: SECURITY,
    match: 'Meridian',
    matchDescription: 'Security operations software',
    legallyWeighted: true,
    expect: { maxOverall: 55, severityAtMost: 'medium' },
    tags: ['distinct'],
    note: 'Shares a trailing sound but is plainly a different word.',
  },
  {
    id: 'distinct-004',
    kind: 'clear',
    candidate: 'Figma',
    category: 'saas',
    description: 'Design and prototyping tool',
    match: 'Photoshop',
    matchDescription: 'Image editing and graphics software',
    legallyWeighted: true,
    expect: { maxOverall: 45, severityAtMost: 'low' },
    tags: ['distinct', 'same-industry'],
    note: 'Direct competitors with unrelated names are not a naming conflict.',
  },
  {
    id: 'distinct-005',
    kind: 'clear',
    candidate: 'Keyora',
    category: 'saas',
    description: SECURITY,
    match: 'Zebra',
    matchDescription: 'Enterprise security tooling',
    legallyWeighted: true,
    expect: { maxOverall: 45, severityAtMost: 'low' },
    tags: ['distinct'],
    note: 'Short unrelated word in the same field.',
  },

  /* ── shared prefix or suffix only ─────────────────────────────────────── */
  {
    id: 'affix-001',
    kind: 'clear',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envelope',
    matchDescription: 'Document management software',
    legallyWeighted: true,
    expect: { maxOverall: 60, severityAtMost: 'medium' },
    tags: ['shared-prefix'],
    note: 'Three shared opening letters do not make a confusable brand.',
  },
  {
    id: 'affix-002',
    kind: 'clear',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Environment Canada',
    matchDescription: 'Government environmental agency',
    expect: { maxOverall: 60, severityAtMost: 'medium' },
    tags: ['shared-prefix', 'containment-false-positive'],
    note: 'A prefix match mid-word must not be treated as containment.',
  },
  {
    id: 'affix-003',
    kind: 'clear',
    candidate: 'Stripe',
    category: 'saas',
    description: 'Payment processing platform',
    match: 'Pinstriped Suits',
    matchDescription: 'Menswear tailoring retailer',
    expect: { maxOverall: 60, severityAtMost: 'medium' },
    tags: ['shared-substring', 'containment-false-positive'],
    note: 'A substring inside a longer word is not a word-boundary match.',
  },
  {
    id: 'affix-004',
    kind: 'clear',
    candidate: 'Lyft',
    category: 'mobile_app',
    description: 'Ride hailing app',
    match: 'Shoplifter',
    matchDescription: 'Retail loss prevention software',
    expect: { maxOverall: 55, severityAtMost: 'medium' },
    tags: ['shared-substring'],
    note: 'Contains the letters, shares nothing meaningful.',
  },

  /* ── numeric and digit-bearing names ──────────────────────────────────── */
  {
    id: 'digits-001',
    kind: 'clear',
    candidate: 'Web3Labs',
    category: 'saas',
    description: 'Blockchain developer tooling',
    match: 'WebeLabs',
    matchDescription: 'Web design consultancy',
    expect: { maxOverall: 90, severityAtMost: 'high' },
    tags: ['digits'],
    note: 'Regression guard: digits must not be folded to letters in the key.',
  },
  {
    id: 'digits-002',
    kind: 'clear',
    candidate: '3M',
    category: 'business',
    description: 'Industrial manufacturing conglomerate',
    match: 'EM',
    matchDescription: 'Marketing consultancy',
    expect: { severityAtMost: 'high' },
    tags: ['digits'],
    note: 'A digit-led name must not collapse into a letter-led one.',
  },

  /* ── unknown industry must stay unknown ───────────────────────────────── */
  {
    id: 'unknown-001',
    kind: 'clear',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envryn',
    expect: { industryUnknown: true },
    tags: ['unknown-industry'],
    note: 'No description at all. Relevance must be undefined, never guessed.',
  },
  {
    id: 'unknown-002',
    kind: 'clear',
    candidate: 'Envryn',
    category: 'other',
    match: 'Envryn',
    matchDescription: 'Computer security software',
    expect: { industryUnknown: true },
    tags: ['unknown-industry'],
    note: 'Category "other" with no description seeds nothing, so relevance is unknowable.',
  },
  {
    id: 'unknown-003',
    kind: 'clear',
    candidate: 'Keyora',
    category: 'saas',
    description: SECURITY,
    match: 'Keyora',
    matchDescription: 'lorem ipsum dolor sit amet consectetur',
    expect: { industryUnknown: true },
    tags: ['unknown-industry'],
    note: 'Unclassifiable prose must not be forced into a taxonomy node.',
  },

  /* ── company registers: contained but not the head, or not the field ───── */
  {
    id: 'registry-003',
    kind: 'clear',
    candidate: 'Monzo',
    category: 'finance',
    description: BANKING,
    match: 'Monzo Tyres',
    matchCategories: ['automotive'],
    active: true,
    legallyWeighted: true,
    expect: { maxIndustry: 40, severityAtMost: 'low' },
    tags: ['registry', 'containment', 'cross-category'],
    note:
      'Leading containment on its own must not escalate. A tyre fitter shares the ' +
      'word but not the field, and telling a fintech founder this blocks their name ' +
      'would be the false alarm that makes the whole report untrustworthy.',
  },
  {
    id: 'registry-004',
    kind: 'clear',
    candidate: 'Monzo',
    category: 'finance',
    description: BANKING,
    match: 'Kids Monzo',
    matchCategories: ['entertainment'],
    active: true,
    legallyWeighted: true,
    expect: { severityAtMost: 'low' },
    tags: ['registry', 'containment', 'trailing'],
    note:
      'Contains the candidate as a modifier rather than as the head of the name. ' +
      'Weaker evidence than "Monzo Bank" and must score that way, which is the ' +
      'distinction `leadsWithName` exists to draw.',
  },
  {
    id: 'registry-005',
    kind: 'clear',
    candidate: 'Monzo',
    category: 'finance',
    description: BANKING,
    match: 'Monzo Books',
    matchCategories: ['retail'],
    active: false,
    legallyWeighted: true,
    expect: { severityAtMost: 'low' },
    tags: ['registry', 'containment', 'inactive'],
    note:
      'Dissolved. A struck-off company is worth showing as context and worth ' +
      'nothing as an obstacle, so the inactive penalty must survive the ' +
      'containment floor rather than being overridden by it.',
  },
]
