/**
 * Conflict cases — names that genuinely collide.
 *
 * Failing any of these is a **false negative**: the engine told somebody a
 * problematic name looked fine. §54 calls this the most important metric, and
 * it is the failure mode that would actually harm a user.
 */
import type { GoldenCase } from './types'

const SECURITY = 'Secure developer secrets manager with encryption'
const PAYMENTS = 'Payment processing platform for developers'
const BANKING = 'Mobile banking app and current account'

export const CONFLICT_CASES: GoldenCase[] = [
  /* ── exact collisions ─────────────────────────────────────────────────── */
  {
    id: 'exact-001',
    kind: 'conflict',
    candidate: 'Stripe',
    category: 'saas',
    description: PAYMENTS,
    match: 'Stripe',
    matchDescription: 'Payment processing and financial infrastructure company',
    legallyWeighted: true,
    expect: { minOverall: 95, minText: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'famous-brand', 'same-industry'],
    note: 'Identical name, identical field. If anything is critical, this is.',
  },
  {
    id: 'exact-002',
    kind: 'conflict',
    candidate: 'Slack',
    category: 'saas',
    description: 'Team messaging and chat for workplaces',
    match: 'Slack',
    matchDescription: 'Business messaging and chat platform',
    legallyWeighted: true,
    expect: { minOverall: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'famous-brand', 'same-industry'],
    note: 'Exact famous brand in exactly its own category.',
  },
  {
    id: 'exact-003',
    kind: 'conflict',
    candidate: 'Figma',
    category: 'saas',
    description: 'Design and prototyping tool',
    match: 'Figma',
    matchDescription: 'Collaborative interface design and prototyping software',
    legallyWeighted: true,
    expect: { minOverall: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'famous-brand', 'same-industry'],
    note: 'Exact match in design tooling.',
  },
  {
    id: 'exact-004',
    kind: 'conflict',
    candidate: 'Vercel',
    category: 'developer_tool',
    description: 'Deployment and hosting infrastructure',
    match: 'Vercel',
    matchDescription: 'Cloud hosting and deployment infrastructure platform',
    legallyWeighted: true,
    expect: { minOverall: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'famous-brand', 'same-industry'],
    note: 'Exact match in devops hosting.',
  },
  {
    id: 'exact-005',
    kind: 'conflict',
    candidate: 'Notion',
    category: 'saas',
    description: 'Notes and workflow collaboration',
    match: 'Notion',
    matchDescription: 'Notes, documents and project management software',
    legallyWeighted: true,
    expect: { minOverall: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'famous-brand', 'same-industry'],
    note: 'Exact match in productivity software.',
  },
  {
    id: 'exact-006',
    kind: 'conflict',
    candidate: 'Vaultara',
    category: 'saas',
    description: SECURITY,
    match: 'Vaultara',
    matchDescription: 'Password and secrets management software',
    legallyWeighted: true,
    expect: { minOverall: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'invented-name', 'same-industry'],
    note: 'Invented names collide too; rarity is not protection once taken.',
  },
  {
    id: 'exact-007',
    kind: 'conflict',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'ENVRYN',
    matchDescription: 'Computer security software and encryption services',
    legallyWeighted: true,
    expect: { minOverall: 95, minText: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'case-difference', 'same-industry'],
    note: 'Case must never affect the verdict.',
  },
  {
    id: 'exact-008',
    kind: 'conflict',
    candidate: 'Env Ryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envryn',
    matchDescription: 'Security and encryption platform',
    legallyWeighted: true,
    expect: { minOverall: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'separator', 'same-industry'],
    note: 'Spacing must not hide an identical name.',
  },
  {
    id: 'exact-009',
    kind: 'conflict',
    candidate: 'Env-Ryn',
    category: 'saas',
    description: SECURITY,
    match: 'envryn',
    matchDescription: 'Encryption and secrets software',
    legallyWeighted: true,
    expect: { minOverall: 95, severityAtLeast: 'critical' },
    tags: ['exact', 'separator', 'same-industry'],
    note: 'Hyphenation must not hide an identical name.',
  },
  {
    id: 'exact-010',
    kind: 'conflict',
    candidate: 'Lockryn',
    category: 'saas',
    description: SECURITY,
    match: 'Lockryn',
    matchDescription: 'Authentication and password security tools',
    legallyWeighted: true,
    expect: { minOverall: 95, minIndustry: 70, severityAtLeast: 'critical' },
    tags: ['exact', 'invented-name', 'same-industry'],
    note: 'Exact invented-name collision in security.',
  },

  /* ── near-miss spellings ──────────────────────────────────────────────── */
  {
    id: 'near-001',
    kind: 'conflict',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envrin',
    matchDescription: 'Computer security software',
    legallyWeighted: true,
    expect: { minOverall: 75, minText: 75, severityAtLeast: 'high' },
    tags: ['near-miss', 'vowel-swap', 'same-industry'],
    note: 'One vowel apart in the same field — the roadmap motivating example.',
  },
  {
    id: 'near-002',
    kind: 'conflict',
    candidate: 'Stripe',
    category: 'saas',
    description: PAYMENTS,
    match: 'Strype',
    matchDescription: 'Payment processing services',
    legallyWeighted: true,
    expect: { minOverall: 70, severityAtLeast: 'high' },
    tags: ['near-miss', 'vowel-swap', 'same-industry'],
    note: 'i/y substitution is the commonest brand respelling there is.',
  },
  {
    id: 'near-003',
    kind: 'conflict',
    candidate: 'Vaultara',
    category: 'saas',
    description: SECURITY,
    match: 'Vaultera',
    matchDescription: 'Secrets management platform',
    legallyWeighted: true,
    expect: { minOverall: 80, severityAtLeast: 'high' },
    tags: ['near-miss', 'vowel-swap', 'same-industry'],
    note: 'Single-letter difference in a long invented name.',
  },
  {
    id: 'near-004',
    kind: 'conflict',
    candidate: 'Keyora',
    category: 'saas',
    description: SECURITY,
    match: 'Keyoro',
    matchDescription: 'Encryption key management software',
    legallyWeighted: true,
    expect: { minOverall: 75, severityAtLeast: 'high' },
    tags: ['near-miss', 'vowel-swap', 'same-industry'],
    note: 'Final-vowel difference; reads and sounds nearly identical.',
  },
  {
    id: 'near-005',
    kind: 'conflict',
    candidate: 'Cloudflare',
    category: 'saas',
    description: 'Content delivery network and infrastructure',
    match: 'Cloudflaire',
    matchDescription: 'CDN and cloud infrastructure services',
    legallyWeighted: true,
    expect: { minOverall: 80, severityAtLeast: 'high' },
    tags: ['near-miss', 'inserted-letter', 'same-industry'],
    note: 'Inserted letter in a well-known infrastructure brand.',
  },
  {
    id: 'near-006',
    kind: 'conflict',
    candidate: 'Datadog',
    category: 'saas',
    description: 'Monitoring and observability platform',
    match: 'Datadawg',
    matchDescription: 'Infrastructure monitoring and metrics',
    legallyWeighted: true,
    expect: { minOverall: 60, severityAtLeast: 'medium' },
    tags: ['near-miss', 'same-industry'],
    note: 'Deliberate respelling of a monitoring brand.',
  },
  {
    id: 'near-007',
    kind: 'conflict',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envrynn',
    matchDescription: 'Security software vendor',
    legallyWeighted: true,
    expect: { minOverall: 80, severityAtLeast: 'high' },
    tags: ['near-miss', 'doubled-letter', 'same-industry'],
    note: 'Doubled trailing consonant, the "dribbble" pattern.',
  },
  {
    id: 'near-008',
    kind: 'conflict',
    candidate: 'Keyora',
    category: 'saas',
    description: SECURITY,
    match: 'Keyoras',
    matchDescription: 'Key management and encryption tools',
    legallyWeighted: true,
    expect: { minOverall: 80, severityAtLeast: 'high' },
    tags: ['near-miss', 'plural', 'same-industry'],
    note: 'A trailing s must not read as a different brand.',
  },
  {
    id: 'near-009',
    kind: 'conflict',
    candidate: 'Sentry',
    category: 'developer_tool',
    description: 'Error tracking and monitoring for applications',
    match: 'Sentrie',
    matchDescription: 'Application error monitoring service',
    legallyWeighted: true,
    expect: { minOverall: 65, severityAtLeast: 'medium' },
    tags: ['near-miss', 'same-industry'],
    note: 'Phonetically identical respelling of a developer tool.',
  },
  {
    id: 'near-010',
    kind: 'conflict',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envryn Security',
    matchDescription: 'Computer security software company',
    legallyWeighted: true,
    expect: { minIndustry: 70, severityAtLeast: 'medium' },
    tags: ['near-miss', 'suffix', 'same-industry'],
    note: 'The candidate appears verbatim with a descriptive suffix.',
  },

  /* ── transpositions and typos ─────────────────────────────────────────── */
  {
    id: 'typo-001',
    kind: 'conflict',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envrny',
    matchDescription: 'Security tooling vendor',
    legallyWeighted: true,
    expect: { minOverall: 70, severityAtLeast: 'medium' },
    tags: ['typo', 'transposition', 'same-industry'],
    note: 'A transposition is one edit to a human and must not read as two.',
  },
  {
    id: 'typo-002',
    kind: 'conflict',
    candidate: 'Vaultara',
    category: 'saas',
    description: SECURITY,
    match: 'Vualtara',
    matchDescription: 'Secrets vault software',
    legallyWeighted: true,
    expect: { minOverall: 70, severityAtLeast: 'medium' },
    tags: ['typo', 'transposition', 'same-industry'],
    note: 'Adjacent transposition early in the word.',
  },
  {
    id: 'typo-003',
    kind: 'conflict',
    candidate: 'Lockryn',
    category: 'saas',
    description: SECURITY,
    match: 'Lockryen',
    matchDescription: 'Password management software',
    legallyWeighted: true,
    expect: { minOverall: 70, severityAtLeast: 'medium' },
    tags: ['typo', 'same-industry'],
    note: 'Inserted vowel near the end.',
  },

  /* ── phonetic collisions (spelling differs, sound does not) ───────────── */
  {
    id: 'phon-001',
    kind: 'conflict',
    candidate: 'Fyre',
    category: 'saas',
    description: 'Event and ticketing platform',
    match: 'Fire',
    matchDescription: 'Event ticketing and booking software',
    legallyWeighted: true,
    expect: { minPhonetic: 85, severityAtLeast: 'high' },
    tags: ['phonetic', 'same-industry'],
    note: 'Homophone with entirely different spelling.',
  },
  {
    id: 'phon-002',
    kind: 'conflict',
    candidate: 'Lyft',
    category: 'mobile_app',
    description: 'Ride hailing and transport app',
    match: 'Lift',
    matchDescription: 'Ride sharing and transport application',
    legallyWeighted: true,
    expect: { minPhonetic: 85, severityAtLeast: 'high' },
    tags: ['phonetic', 'same-industry'],
    note: 'The canonical y-for-i brand respelling.',
  },
  {
    id: 'phon-003',
    kind: 'conflict',
    candidate: 'Smyth',
    category: 'business',
    description: 'Professional consulting services',
    match: 'Smith',
    matchDescription: 'Business advisory and consulting firm',
    legallyWeighted: true,
    expect: { minPhonetic: 90, severityAtLeast: 'high' },
    tags: ['phonetic', 'same-industry'],
    note: 'Textbook Double Metaphone equivalence.',
  },
  {
    id: 'phon-004',
    kind: 'conflict',
    candidate: 'Kwik',
    category: 'ecommerce',
    description: 'Fast online retail delivery',
    match: 'Quick',
    matchDescription: 'Rapid online retail and delivery service',
    legallyWeighted: true,
    expect: { minPhonetic: 70, severityAtLeast: 'medium' },
    tags: ['phonetic', 'same-industry'],
    note: 'kw/qu substitution sounds identical.',
  },
  {
    id: 'phon-005',
    kind: 'conflict',
    candidate: 'Fotoly',
    category: 'mobile_app',
    description: 'Photo editing application',
    match: 'Photoly',
    matchDescription: 'Photo editing and graphics app',
    legallyWeighted: true,
    expect: { minPhonetic: 80, severityAtLeast: 'high' },
    tags: ['phonetic', 'same-industry'],
    note: 'ph/f substitution, a common brand simplification.',
  },
  {
    id: 'phon-006',
    kind: 'conflict',
    candidate: 'Zeneth',
    category: 'saas',
    description: 'Analytics and reporting platform',
    match: 'Zenith',
    matchDescription: 'Business intelligence and analytics software',
    legallyWeighted: true,
    expect: { minPhonetic: 80, severityAtLeast: 'high' },
    tags: ['phonetic', 'same-industry'],
    note: 'Vowel change with no audible difference.',
  },

  /* ── lookalike / homoglyph squatting ──────────────────────────────────── */
  {
    id: 'homo-001',
    kind: 'conflict',
    candidate: 'paypal',
    category: 'saas',
    description: PAYMENTS,
    match: 'pаypal',
    matchDescription: 'Online payment processing service',
    legallyWeighted: true,
    expect: { minOverall: 95, minText: 95, severityAtLeast: 'critical' },
    tags: ['homoglyph', 'squatting', 'same-industry'],
    note: 'Cyrillic а renders identically to Latin a. A real spoofing vector.',
  },
  {
    id: 'homo-002',
    kind: 'conflict',
    candidate: 'google',
    category: 'saas',
    description: 'Search and advertising platform',
    match: 'gοogle',
    matchDescription: 'Internet search and advertising company',
    legallyWeighted: true,
    expect: { minOverall: 95, severityAtLeast: 'critical' },
    tags: ['homoglyph', 'squatting', 'same-industry'],
    note: 'Greek omicron substituted for Latin o.',
  },
  {
    id: 'homo-003',
    kind: 'conflict',
    candidate: 'Stripe',
    category: 'saas',
    description: PAYMENTS,
    match: 'Ｓtripe',
    matchDescription: 'Payment processing platform',
    legallyWeighted: true,
    expect: { minOverall: 95, severityAtLeast: 'critical' },
    tags: ['homoglyph', 'fullwidth', 'same-industry'],
    note: 'Full-width Latin S; NFKD folding must collapse it.',
  },
  {
    id: 'homo-004',
    kind: 'conflict',
    candidate: 'Cafe',
    category: 'restaurant',
    description: 'Coffee shop and bakery',
    match: 'Café',
    matchDescription: 'Coffee shop and cafe chain',
    legallyWeighted: true,
    expect: { minOverall: 95, severityAtLeast: 'critical' },
    tags: ['homoglyph', 'diacritic', 'same-industry'],
    note: 'A diacritic must not create a distinct brand.',
  },

  /* ── contained names ──────────────────────────────────────────────────── */
  {
    id: 'contain-001',
    kind: 'conflict',
    candidate: 'Vault',
    category: 'developer_tool',
    description: SECURITY,
    match: 'HashiCorp Vault',
    matchDescription: 'Secrets management and encryption tool',
    matchCategories: ['repository'],
    legallyWeighted: true,
    expect: { minIndustry: 50, severityAtLeast: 'low' },
    tags: ['containment', 'same-industry'],
    note: 'The candidate is a whole word inside an established product name.',
  },
  {
    id: 'contain-002',
    kind: 'conflict',
    candidate: 'Stripe',
    category: 'saas',
    description: PAYMENTS,
    match: 'Stripe Dashboard',
    matchDescription: 'Payment management and reporting application',
    legallyWeighted: true,
    expect: { minIndustry: 50, severityAtLeast: 'low' },
    tags: ['containment', 'same-industry'],
    note: 'Length asymmetry drags similarity down; relevance must not follow.',
  },

  /* ── inactive conflicts (real, but weaker) ────────────────────────────── */
  {
    id: 'inactive-001',
    kind: 'conflict',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envryn',
    matchDescription: 'Defunct computer security software project',
    active: false,
    legallyWeighted: true,
    expect: { minOverall: 95, severityAtLeast: 'medium', severityAtMost: 'high' },
    tags: ['inactive', 'same-industry'],
    note: 'A dead project is evidence worth showing, not a blocker. Stepped down.',
  },
  {
    id: 'inactive-002',
    kind: 'conflict',
    candidate: 'Keyora',
    category: 'developer_tool',
    description: SECURITY,
    match: 'keyora',
    matchDescription: 'Archived encryption library',
    matchCategories: ['repository'],
    active: false,
    legallyWeighted: false,
    expect: { minOverall: 95, severityAtLeast: 'low' },
    tags: ['inactive', 'same-industry'],
    note: 'An archived repo still holds the namespace.',
  },

  /* ── cross-category collisions within one sector ──────────────────────── */
  {
    id: 'neighbour-001',
    kind: 'conflict',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envryn',
    matchDescription: 'Open source developer SDK and CLI tooling',
    matchCategories: ['repository'],
    legallyWeighted: true,
    expect: { minOverall: 95, minIndustry: 40, maxIndustry: 80, severityAtLeast: 'high' },
    tags: ['neighbouring-field', 'exact'],
    note: 'Security and developer tools are adjacent, not identical. Mid relevance.',
  },
  {
    id: 'neighbour-002',
    kind: 'conflict',
    candidate: 'Pixelforge',
    category: 'game',
    description: 'Indie game studio and puzzle games',
    match: 'Pixelforge',
    matchDescription: 'Entertainment and film production studio',
    legallyWeighted: true,
    expect: { minOverall: 95, severityAtLeast: 'high' },
    tags: ['neighbouring-field', 'exact'],
    note: 'Games and entertainment sit in different sectors but overlap in practice.',
  },

  /* ── company registers: the candidate is the head of a longer legal name ─ */
  {
    id: 'registry-001',
    kind: 'conflict',
    candidate: 'Monzo',
    category: 'finance',
    description: BANKING,
    match: 'Monzo Bank',
    matchCategories: ['banking'],
    active: true,
    legallyWeighted: true,
    expect: { minIndustry: 70, severityAtLeast: 'high' },
    tags: ['registry', 'containment', 'leading', 'same-industry'],
    note:
      'The real case this rule was built for. Length asymmetry drags the blended ' +
      'similarity to roughly 54, so the floor alone hid an active UK bank trading ' +
      'under the exact candidate name. The candidate is the head of the name and ' +
      'the field matches, which is a serious obstacle however the string scores.',
  },
  {
    id: 'registry-002',
    kind: 'conflict',
    candidate: 'Envryn',
    category: 'saas',
    description: SECURITY,
    match: 'Envryn Security',
    matchCategories: ['security'],
    active: true,
    legallyWeighted: true,
    expect: { minIndustry: 70, severityAtLeast: 'high' },
    tags: ['registry', 'containment', 'leading', 'same-industry'],
    note:
      'The invented-name version of registry-001, so the rule is not tuned to one ' +
      'famous brand. Candidate plus an industry descriptor, same field, active.',
  },
]
